package modelo;
// Generated 11-05-2015 04:02:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private int rut;
     private String dvRut;
     private String razonSocial;
     private String direccion;
     private String comuna;
     private String ciudad;
     private String giro;
     private String telefono;
     private String emailContacto;
     private Boolean deshabilitado;
     private byte tipoCliente;

    public Cliente() {
    }

    public Cliente(Integer codCliente, int rut, String dvRut, String razonSocial, String direccion, String comuna, String ciudad, String giro, String telefono, String emailContacto, Boolean deshabilitado, byte tipo_cliente) {
        this.codCliente = codCliente;
        this.rut = rut;
        this.dvRut = dvRut;
        this.razonSocial = razonSocial;
        this.direccion = direccion;
        this.comuna = comuna;
        this.ciudad = ciudad;
        this.giro = giro;
        this.telefono = telefono;
        this.emailContacto = emailContacto;
        this.deshabilitado = deshabilitado;
        this.tipoCliente=tipo_cliente;
    }

	
    
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public int getRut() {
        return this.rut;
    }
    
    public void setRut(int rut) {
        this.rut = rut;
    }

    public String getDvRut() {
        return dvRut;
    }

    public void setDvRut(String dvRut) {
        this.dvRut = dvRut;
    }
    

    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getComuna() {
        return this.comuna;
    }
    
    public void setComuna(String comuna) {
        this.comuna = comuna;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmailContacto() {
        return this.emailContacto;
    }
    
    public void setEmailContacto(String emailContacto) {
        this.emailContacto = emailContacto;
    }
    public Boolean getDeshabilitado() {
        return this.deshabilitado;
    }
    
    public void setDeshabilitado(Boolean deshabilitado) {
        this.deshabilitado = deshabilitado;
    }

    public byte getTipoCliente() {
        return tipoCliente;
    }

    public void setTipoCliente(byte tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    
   




}


